services:
  # 1. DATABASE (Postgres) - Port digeser ke 5433 agar tidak bentrok dengan Lapisbaja
  db:
    image: postgres:15-alpine
    container_name: bookinaja_db
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: bookinaja_db
    ports:
      - "5433:5432" # Luar: 5433, Dalam: 5432
    volumes:
      - bookinaja_postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  # 2. CACHE (Redis) - Port digeser ke 6380
  redis:
    image: redis:alpine
    container_name: bookinaja_redis
    restart: always
    ports:
      - "6380:6379" # Luar: 6380, Dalam: 6379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  # 3. BACKEND (Go) - Port digeser ke 8081
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bookinaja_api
    restart: always
    ports:
      - "8081:8080" # Luar: 8081, Dalam: 8080
    env_file: ./backend/.env
    environment:
      MIGRATION_PATH: /app/migrations
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  # 4. FRONTEND (Next.js) - Port digeser ke 3001
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bookinaja_fe
    restart: always
    ports:
      - "3001:3000" # Luar: 3001, Dalam: 3000
    env_file: ./frontend/.env
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

# Nama volume harus dibedakan dengan proyek sebelah agar data tidak tertimpa
volumes:
  bookinaja_postgres_data:
