ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS discovery_featured BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS discovery_promoted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS promo_starts_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS promo_ends_at TIMESTAMPTZ NULL;
