ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS internal_note TEXT,
    ADD COLUMN IF NOT EXISTS rescheduled_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS reschedule_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS no_show_at TIMESTAMP WITH TIME ZONE;
