name: Deploy Monorepo to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Masuk ke folder monorepo di EC2
            cd ~/bookinaja || (git clone https://github.com/helwyza-f/bookinaja.git ~/bookinaja && cd ~/bookinaja)

            # Paksa ambil kode terbaru dari branch main
            git fetch origin main
            git reset --hard origin/main

            # Injeksi environment variables dari GitHub Secrets
            echo "${{ secrets.BE_ENV }}" > saas/.env
            echo "${{ secrets.FE_ENV }}" > saas-app/.env

            # Bersihkan container lama agar port tidak bentrok
            sudo docker-compose down

            # Bangun ulang image dan jalankan di background
            # Note: Ini akan memakan waktu karena build Next.js cukup berat di t3.micro
            sudo docker-compose up --build -d

            # Hapus image lama yang tidak terpakai (dangling images)
            sudo docker image prune -f
